using System;
using System.Collections.Generic;
using System.Linq;

namespace eulerproblems
{
    class Program
    {
        /*
         Task 1:
        If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
        Find the sum of all the multiples of 3 or 5 below 1000.
        Task 2: 
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        */
        static void Main(string[] args)
        {
            ProblemOne();
            ProblemTwo();
            ProblemThree();
        }

        private static void ProblemOne()
        {
            var sum = Enumerable.Range(0, 1000).Where(n => n % 3 == 0 || n % 5 == 0).Sum();
            Console.WriteLine(sum);
        }

        private static void ProblemTwo()
        {
            int first = 1;
            int second = 1;
            int newTerm = 0;
            int sum = 0;

            while (newTerm <= 4000000)
            {
                newTerm = first + second;

                if (newTerm % 2 == 0)
                {
                    sum += newTerm;
                }

                first = second;
                second = newTerm;
            }

            Console.WriteLine(sum);
        }

        private static void ProblemThree()
        {
            int b;
            long a;
            var intList = new List<int>();
            a = 600851475143;

            for (b = 2; a > 1; b++)
                if (a % b == 0)
                {
                    int x = 0;
                    while (a % b == 0)
                    {
                        a /= b;
                        x++;
                    }
                    intList.Add(b);
                }
            Console.WriteLine(intList.Max());
        }
    }
}
